
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bachelor
 */
public class UniversityGUI extends javax.swing.JFrame {

    /**
     * Creates new form UniversityGUI
     */
    public UniversityGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddInstructorPanel = new javax.swing.JPanel();
        INameLbl = new javax.swing.JLabel();
        instructorIdLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        INameTxt = new javax.swing.JTextField();
        IIdTxt = new javax.swing.JTextField();
        ILastNametxt = new javax.swing.JTextField();
        IGenderCmbox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        IlistPanel = new javax.swing.JList<>();
        IAddBtn = new javax.swing.JButton();
        ICancelBtn = new javax.swing.JButton();
        IDeleteBtn = new javax.swing.JButton();
        IUpdateBtn = new javax.swing.JButton();
        StudentPanel = new javax.swing.JPanel();
        lastNameField = new javax.swing.JTextField();
        dateOfBirthField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        firstNameField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        CoursePanel = new javax.swing.JPanel();
        courseNameLbl = new javax.swing.JLabel();
        CnameTxt = new javax.swing.JTextField();
        CnumberLbl = new javax.swing.JLabel();
        cnumberTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        AddcourseBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        AddStudentCommand = new javax.swing.JMenuItem();
        dStudent = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addInstructor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to CIT Management System");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        AddInstructorPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                AddInstructorPanelComponentShown(evt);
            }
        });

        INameLbl.setText("Instructor name");

        instructorIdLbl.setText("Instructor ID");

        jLabel7.setText("Instructor Surname");

        jLabel8.setText("Gender");

        INameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                INameTxtFocusLost(evt);
            }
        });
        INameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INameTxtActionPerformed(evt);
            }
        });

        IIdTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IIdTxtFocusLost(evt);
            }
        });

        ILastNametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ILastNametxtFocusLost(evt);
            }
        });
        ILastNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ILastNametxtActionPerformed(evt);
            }
        });

        IGenderCmbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        IlistPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IlistPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IlistPanelMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(IlistPanel);

        IAddBtn.setText("ADD");
        IAddBtn.setEnabled(false);
        IAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IAddBtnActionPerformed(evt);
            }
        });

        ICancelBtn.setText("Cancel");
        ICancelBtn.setEnabled(false);
        ICancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICancelBtnActionPerformed(evt);
            }
        });

        IDeleteBtn.setText("Delete");
        IDeleteBtn.setEnabled(false);
        IDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDeleteBtnActionPerformed(evt);
            }
        });

        IUpdateBtn.setText("Update");
        IUpdateBtn.setEnabled(false);
        IUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IUpdateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddInstructorPanelLayout = new javax.swing.GroupLayout(AddInstructorPanel);
        AddInstructorPanel.setLayout(AddInstructorPanelLayout);
        AddInstructorPanelLayout.setHorizontalGroup(
            AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddInstructorPanelLayout.createSequentialGroup()
                .addGroup(AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddInstructorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(INameLbl)
                            .addComponent(instructorIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(44, 44, 44)
                        .addGroup(AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IGenderCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IIdTxt)
                            .addComponent(ILastNametxt)
                            .addComponent(INameTxt))
                        .addGap(123, 123, 123)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddInstructorPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(IAddBtn)
                        .addGap(47, 47, 47)
                        .addComponent(ICancelBtn)
                        .addGap(40, 40, 40)
                        .addComponent(IDeleteBtn)
                        .addGap(37, 37, 37)
                        .addComponent(IUpdateBtn)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        AddInstructorPanelLayout.setVerticalGroup(
            AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddInstructorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddInstructorPanelLayout.createSequentialGroup()
                        .addGroup(AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(INameLbl)
                            .addComponent(INameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instructorIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ILastNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(IGenderCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(AddInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IAddBtn)
                    .addComponent(ICancelBtn)
                    .addComponent(IDeleteBtn)
                    .addComponent(IUpdateBtn))
                .addGap(35, 35, 35))
        );

        getContentPane().add(AddInstructorPanel, "card13");

        StudentPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                StudentPanelComponentShown(evt);
            }
        });

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Date of birth");

        jLabel4.setText("Gender");

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
                updateElement(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        addButton.setText("Add");
        addButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addButtonComponentShown(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.setEnabled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.setEnabled(false);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGroup(StudentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)))
                        .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(dateOfBirthField))
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(StudentPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentPanelLayout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addGap(51, 51, 51)
                        .addComponent(updateButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentPanelLayout.createSequentialGroup()
                        .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelButton)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(StudentPanel, "card3");

        courseNameLbl.setText("Course Name:");

        CnumberLbl.setText("Course Number:");

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList2MousePressed(evt);
            }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        AddcourseBtn.setText("Add");
        AddcourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddcourseBtnActionPerformed(evt);
            }
        });

        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.setEnabled(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.setEnabled(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CoursePanelLayout = new javax.swing.GroupLayout(CoursePanel);
        CoursePanel.setLayout(CoursePanelLayout);
        CoursePanelLayout.setHorizontalGroup(
            CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseNameLbl)
                    .addComponent(CnumberLbl))
                .addGap(18, 18, 18)
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CnameTxt)
                        .addComponent(cnumberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addGroup(CoursePanelLayout.createSequentialGroup()
                        .addComponent(AddcourseBtn)
                        .addGap(45, 45, 45)
                        .addComponent(CancelBtn)
                        .addGap(38, 38, 38)
                        .addComponent(deleteBtn)))
                .addGap(18, 18, 18)
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateBtn)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        CoursePanelLayout.setVerticalGroup(
            CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseNameLbl))
                .addGap(30, 30, 30)
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CnumberLbl)
                    .addComponent(cnumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddcourseBtn)
                    .addComponent(CancelBtn)
                    .addComponent(deleteBtn)
                    .addComponent(updateBtn))
                .addGap(64, 64, 64))
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(CoursePanel, "card4");

        Menu1.setText("Students");

        AddStudentCommand.setText("Add Students");
        AddStudentCommand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddStudentCommandMouseClicked(evt);
            }
        });
        AddStudentCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentCommandActionPerformed(evt);
            }
        });
        Menu1.add(AddStudentCommand);

        dStudent.setText("Delete Student");
        dStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dStudentActionPerformed(evt);
            }
        });
        Menu1.add(dStudent);

        jMenuBar1.add(Menu1);

        jMenu2.setText("Instructors");

        addInstructor.setText("Add Instructor");
        addInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstructorActionPerformed(evt);
            }
        });
        jMenu2.add(addInstructor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Courses");

        jMenuItem1.setText("manageCourses");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Exit");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu4.add(exit);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddStudentCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentCommandActionPerformed
        // This are the instructions that add a student
        StudentPanel.setVisible(true);
        AddInstructorPanel.setVisible(false);
        CoursePanel.setVisible(false);
    }//GEN-LAST:event_AddStudentCommandActionPerformed

    private void AddStudentCommandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStudentCommandMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStudentCommandMouseClicked

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        // Create an instance of student
        Student student = new Student();
        student.setFName(firstNameField.getText());
        student.setLName(lastNameField.getText());
        student.setDob(dateOfBirthField.getText());
        student.setGender((String) genderComboBox.getSelectedItem());

        // Add student to the list
        ListModel lModel = jList1.getModel();
        DefaultListModel dlm = new DefaultListModel<Object>();
        int total = lModel.getSize();
        for (int x = 0; x < total; x++) {
            dlm.addElement(lModel.getElementAt(x));
        }
        dlm.addElement(student);
        jList1.setModel(dlm);
        //Clearing the text fields for the next entry
        firstNameField.setText("");
        lastNameField.setText("");
        dateOfBirthField.setText("");
        genderComboBox.setSelectedIndex(0);

        // Storing the student data into the Student table in the database
//        Connection conObj = null;
//        conObj = DatabaseManager.getConnection();
//        if (conObj == null) System.out.println("connection is null");
//        Statement stmt = null;
//        String sql = "INSERT INTO `Student` (`fName`, `lName`, `gender`, `dob`) VALUES ('petro', 'papajorgji', 'Male', '1951-07-30')";
//        
//        try{
//        stmt = conObj.createStatement();
//        stmt.executeQuery(sql);
//        }
//        catch(SQLException se){
//      //Handle errors for JDBC
//            System.out.println("Some erros occurred...");
//         se.printStackTrace();
//        }catch(Exception e){
//      //Handle errors for Class.forName
//        e.printStackTrace();
//
//        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void addInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstructorActionPerformed
        // TODO add your handling code here:
        
        AddInstructorPanel.setVisible(true);
        StudentPanel.setVisible(false);
        CoursePanel.setVisible(false);
    }//GEN-LAST:event_addInstructorActionPerformed

    private void dStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dStudentActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_dStudentActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:

        Object object = jList1.getSelectedValue();

        ListModel lModel = jList1.getModel();
        DefaultListModel dlm = new DefaultListModel<Object>();
        int total = lModel.getSize();
        for (int x = 0; x < total; x++) {
            dlm.addElement(lModel.getElementAt(x));
        }

        dlm.removeElement(object);

        jList1.setModel(dlm);
        deleteButton.setEnabled(false);
        updateButton.setEnabled(false);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        int index = jList1.getSelectedIndex();

        int size = jList1.getModel().getSize();

        if (index >= 0 && index < size) {
            deleteButton.setEnabled(true);
            updateButton.setEnabled(true);
        }

    }//GEN-LAST:event_jList1MouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int index = jList1.getSelectedIndex();
        ListModel lModel = jList1.getModel();

        Student student = (Student) lModel.getElementAt(index);
        student.setFName(firstNameField.getText());
        student.setLName(lastNameField.getText());
        student.setGender((String) genderComboBox.getSelectedItem());
        System.out.println(student.getFName());

        DefaultListModel dlm = new DefaultListModel<Object>();
        int total = lModel.getSize();
        for (int x = 0; x < total; x++) {
            dlm.addElement(lModel.getElementAt(x));
        }
        dlm.removeElementAt(index);
        dlm.addElement(student);
        jList1.setModel(lModel);
        //turn off the delete and update buttons
        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);
        
        //setting text fields to empty
        firstNameField.setText("");
        lastNameField.setText("");
        dateOfBirthField.setText("");
        genderComboBox.setSelectedIndex(0);
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void updateElement(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateElement
        // TODO add your handling code here:

        int index = jList1.getSelectedIndex();
        ListModel lModel = jList1.getModel();

        Student student = (Student) lModel.getElementAt(index);

        firstNameField.setText(student.getFName());
        lastNameField.setText(student.getLName());
        dateOfBirthField.setText(student.getDob());
        genderComboBox.setSelectedItem(student.getGender());

    }//GEN-LAST:event_updateElement

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void addButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addButtonComponentShown


    }//GEN-LAST:event_addButtonComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // Establishing connection to the database
        Connection conObj = DatabaseManager.getConnection();


    }//GEN-LAST:event_formComponentShown

    private void AddInstructorPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_AddInstructorPanelComponentShown
        
    }//GEN-LAST:event_AddInstructorPanelComponentShown

    private void StudentPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_StudentPanelComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentPanelComponentShown

    private void AddcourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddcourseBtnActionPerformed
        
          // Create an instance of student
        Courses course = new Courses();
        course.setCName(CnameTxt.getText());
        course.setCNumber(cnumberTxt.getText());
        
        // Add student to the list
        ListModel lModel = jList2.getModel();
        DefaultListModel dlm = new DefaultListModel<Object>();
        int total = lModel.getSize();
        for (int x = 0; x < total; x++) {
            dlm.addElement(lModel.getElementAt(x));
        }
        dlm.addElement(course);
        jList2.setModel(dlm);
        //Clearing the text fields for the next entry
        CnameTxt.setText("");
        cnumberTxt.setText("");
        
    }//GEN-LAST:event_AddcourseBtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        CoursePanel.setVisible(true);
        AddInstructorPanel.setVisible(false);
        StudentPanel.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
         Object object = jList2.getSelectedValue();

        ListModel lModel = jList2.getModel();
        DefaultListModel dlm = new DefaultListModel<Object>();
        int total = lModel.getSize();
        for (int x = 0; x < total; x++) {
            dlm.addElement(lModel.getElementAt(x));
        }

        dlm.removeElement(object);

        jList2.setModel(dlm);
        deleteBtn.setEnabled(false);
        updateBtn.setEnabled(false);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
           int index = jList2.getSelectedIndex();

        int size = jList2.getModel().getSize();

        if (index >= 0 && index < size) {
            deleteBtn.setEnabled(true);
            updateBtn.setEnabled(true);
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int index = jList2.getSelectedIndex();
        ListModel lModel = jList2.getModel();

        Courses course = (Courses) lModel.getElementAt(index);
        course.setCName(CnameTxt.getText());
        course.setCNumber(cnumberTxt.getText());
        
        DefaultListModel dlm = new DefaultListModel<Object>();
        int total = lModel.getSize();
        for (int x = 0; x < total; x++) {
            dlm.addElement(lModel.getElementAt(x));
        }
        dlm.removeElementAt(index);
        dlm.addElement(course);
        jList2.setModel(lModel);
        //turn off the delete and update buttons
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
        
        //setting text fields to empty
        CnameTxt.setText("");
        cnumberTxt.setText("");
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_jList1ValueChanged

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        // TODO add your handling code here:
      //  int index = jList2.getSelectedIndex();
       // ListModel lModel = jList2.getModel();

        //Courses course = (Courses) lModel.getElementAt(index);

      //  CnameTxt.setText(course.getCName());
      //  cnumberTxt.setText(course.getCNumber());
        
    }//GEN-LAST:event_jList2ValueChanged

    private void jList2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MousePressed
        // TODO add your handling code here:
                int index = jList2.getSelectedIndex();
        ListModel lModel = jList2.getModel();

        Courses course = (Courses) lModel.getElementAt(index);

        CnameTxt.setText(course.getCName());
        cnumberTxt.setText(course.getCNumber());
        
    }//GEN-LAST:event_jList2MousePressed

    private void INameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INameTxtActionPerformed

    private void IAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IAddBtnActionPerformed

        // Create an instance of student
        Instructor instructor = new Instructor();
        instructor.setFName(INameTxt.getText());
        instructor.setLName(ILastNametxt.getText());
        instructor.setId(IIdTxt.getText());
        instructor.setGender((String) IGenderCmbox.getSelectedItem());

        // Add student to the list
        ListModel lModel = IlistPanel.getModel();
        DefaultListModel dlm = new DefaultListModel<Object>();
        int total = lModel.getSize();
        for (int x = 0; x < total; x++) {
            dlm.addElement(lModel.getElementAt(x));
        }
        dlm.addElement(instructor);
        IlistPanel.setModel(dlm);
        //Clearing the text fields for the next entry
        INameTxt.setText("");
        ILastNametxt.setText("");
        IIdTxt.setText("");
        IGenderCmbox.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_IAddBtnActionPerformed

    private void ICancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICancelBtnActionPerformed
        // TODO add your handling code here:
        
        INameTxt.setText("");
        ILastNametxt.setText("");
        IIdTxt.setText("");
        IGenderCmbox.setSelectedIndex(0);
    }//GEN-LAST:event_ICancelBtnActionPerformed

    private void ILastNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ILastNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ILastNametxtActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
                
        INameTxt.setText("");
        ILastNametxt.setText("");
        IIdTxt.setText("");
        IGenderCmbox.setSelectedIndex(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void IDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDeleteBtnActionPerformed
      
        Object object = IlistPanel.getSelectedValue();

        ListModel lModel = IlistPanel.getModel();
        DefaultListModel dlm = new DefaultListModel<Object>();
        int total = lModel.getSize();
        for (int x = 0; x < total; x++) {
            dlm.addElement(lModel.getElementAt(x));
        }

        dlm.removeElement(object);

        IlistPanel.setModel(dlm);
        IDeleteBtn.setEnabled(false);
        IUpdateBtn.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_IDeleteBtnActionPerformed

    private void IUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IUpdateBtnActionPerformed
        // TODO add your handling code here:
        int index = IlistPanel.getSelectedIndex();
        ListModel lModel = IlistPanel.getModel();

        Instructor instructor = (Instructor) lModel.getElementAt(index);
        instructor.setFName(INameTxt.getText());
        instructor.setLName(ILastNametxt.getText());
        instructor.setId(IIdTxt.getText());
        instructor.setGender((String) IGenderCmbox.getSelectedItem());


        DefaultListModel dlm = new DefaultListModel<Object>();
        int total = lModel.getSize();
        for (int x = 0; x < total; x++) {
            dlm.addElement(lModel.getElementAt(x));
        }
        dlm.removeElementAt(index);
        dlm.addElement(instructor);
        IlistPanel.setModel(dlm);
        //turn off the delete and update buttons
        IUpdateBtn.setEnabled(false);
        IDeleteBtn.setEnabled(false);
        
        //setting text fields to empty
        INameTxt.setText("");
        ILastNametxt.setText("");
        IIdTxt.setText("");
        IGenderCmbox.setSelectedIndex(0);
    }//GEN-LAST:event_IUpdateBtnActionPerformed

    private void IlistPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IlistPanelMouseClicked
        int index = IlistPanel.getSelectedIndex();

        int size = IlistPanel.getModel().getSize();

        if (index >= 0 && index < size) {
            IDeleteBtn.setEnabled(true);
            IUpdateBtn.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_IlistPanelMouseClicked
    }
    private void IlistPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IlistPanelMousePressed

        int index = IlistPanel.getSelectedIndex();
        ListModel lModel = IlistPanel.getModel();

        Instructor instructor = (Instructor) lModel.getElementAt(index);

        INameTxt.setText(instructor.getFName());
        ILastNametxt.setText(instructor.getLName());
        IIdTxt.setText(instructor.getId());
        IGenderCmbox.setSelectedItem(instructor.getGender());
    }//GEN-LAST:event_IlistPanelMousePressed

    private void ILastNametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ILastNametxtFocusLost
        // TODO add your handling code here:
       if(INameTxt.getText().length()>0 && ILastNametxt.getText().length()>0 && IIdTxt.getText().length()>0){
           IAddBtn.setEnabled(true);
           ICancelBtn.setEnabled(true);
           }
       else {
            IAddBtn.setEnabled(false);
           ICancelBtn.setEnabled(false);
       }
    }//GEN-LAST:event_ILastNametxtFocusLost

    private void IIdTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IIdTxtFocusLost
       if(INameTxt.getText().length()>0 && ILastNametxt.getText().length()>0 && IIdTxt.getText().length()>0){
           IAddBtn.setEnabled(true);
           ICancelBtn.setEnabled(true);
       } 
       else {
            IAddBtn.setEnabled(false);
           ICancelBtn.setEnabled(false);
       }       // TODO add your handling code here:
    }//GEN-LAST:event_IIdTxtFocusLost

    private void INameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_INameTxtFocusLost
       if(INameTxt.getText().length()>0 && ILastNametxt.getText().length()>0 && IIdTxt.getText().length()>0){
           IAddBtn.setEnabled(true);
           ICancelBtn.setEnabled(true);
       }        // TODO add your handling code here:
              else {
            IAddBtn.setEnabled(false);
           ICancelBtn.setEnabled(false);
       }
    }//GEN-LAST:event_INameTxtFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniversityGUI().setVisible(true);
                // StudentPanel.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddInstructorPanel;
    private javax.swing.JMenuItem AddStudentCommand;
    private javax.swing.JButton AddcourseBtn;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField CnameTxt;
    private javax.swing.JLabel CnumberLbl;
    private javax.swing.JPanel CoursePanel;
    private javax.swing.JButton IAddBtn;
    private javax.swing.JButton ICancelBtn;
    private javax.swing.JButton IDeleteBtn;
    private javax.swing.JComboBox<String> IGenderCmbox;
    private javax.swing.JTextField IIdTxt;
    private javax.swing.JTextField ILastNametxt;
    private javax.swing.JLabel INameLbl;
    private javax.swing.JTextField INameTxt;
    private javax.swing.JButton IUpdateBtn;
    private javax.swing.JList<String> IlistPanel;
    private javax.swing.JMenu Menu1;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JMenuItem addInstructor;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cnumberTxt;
    private javax.swing.JLabel courseNameLbl;
    private javax.swing.JMenuItem dStudent;
    private javax.swing.JTextField dateOfBirthField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteButton;
    private javax.swing.JMenuItem exit;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel instructorIdLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
